# Copyright (c) James Hiester
# SPDX-License-Identifier: MPL-2.0

---
defaultBranch: "main"

branches:
  - main

preset: "angular"
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/exec"
  # - [
  #   '@semantic-release/github',
  #   {
  #     'draftRelease': true, 
  #   },
  # ]
  # - [
  #   '@semantic-release/git',
  #   {
  #     'assets': ['CHANGELOG.md', 'package.json', 'npm-shrinkwrap.json'],  # Files to include in the release commit
  #     'message': 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',  # Custom commit message
  #   },
  # ]


analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    releaseRules:
    - type: "feat"
      release: "minor"
    - type: "fix"
      release: "patch"
    - type: "breaking"
      release: "major"
    - type: "refactor"
      release: "patch"
    - type: "chore"
      release: "patch"


generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "breaking"
        - "feat"
        - "fix"
        - "chore"
      commitsSort: "header"
    types:
    - type: "feat"
    - section: "Features"
    - type: "fix"
    - section: "Bug Fixes"
    - type: "breaking"
    - section: "Breaking Changes"
    - type: "refactor"
    - hidden: true
    - type: "chore"
    - section: "Chore"
    - type: "docs"
    - hidden: true
    - type: "doc"
    - hidden: true
    - type: "style"
    - hidden: true
    - type: "perf"
    - hidden: true
    - type: "test"
    - hidden: true
    presetConfig: true
  - path: "@semantic-release/exec"
    cmd: "echo ${nextRelease.version} > nextRelease"
# prepare:
#   - path: "@semantic-release/changelog"
#     changelogFile: "CHANGELOG.md"
# publish:
#   - path: "@semantic-release/github"
#     draftRelease: true

# success:
#   - "@semantic-release/github"