package constants

import "time"

const ZERO_UUID = "00000000-0000-0000-0000-000000000000"

const (
	HEADER_LOCATION           = "Location"
	HEADER_OPERATION_LOCATION = "Operation-Location"
	HEADER_RETRY_AFTER        = "Retry-After"
	HTTPS                     = "https"
	API_VERSION_PARAM         = "api-version"
)

const (
	DEFAULT_RESOURCE_OPERATION_TIMEOUT_IN_MINUTES = 20 * time.Minute
	MAX_RETRY_COUNT                               = 10
)

// Error codes for provider errors.
const (
	ERROR_OBJECT_NOT_FOUND             = "OBJECT_NOT_FOUND"
	ERROR_ENVIRONMENT_URL_NOT_FOUND    = "ENVIRONMENT_URL_NOT_FOUND"
	ERROR_ENVIRONMENTS_IN_ENV_GROUP    = "ENVIRONMENTS_IN_ENV_GROUP"
	ERROR_POLICY_ASSIGNED_TO_ENV_GROUP = "POLICY_ASSIGNED_TO_ENV_GROUP"
	ERROR_ENVIRONMENT_SETTINGS_FAILED  = "ENVIRONMENT_SETTINGS_FAILED"
	ERROR_ENVIRONMENT_CREATION         = "ENVIRONMENT_CREATION"
)
